# Generated by Django 2.0.3 on 2018-04-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=20, unique=True, verbose_name='账号')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('question', models.CharField(max_length=40, verbose_name='密保问题')),
                ('answer', models.CharField(max_length=20, verbose_name='密保答案')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('tip', models.CharField(max_length=40, verbose_name='签名')),
                ('modified', models.CharField(max_length=19, verbose_name='变更时间')),
                ('is_delet', models.IntegerField(default=0, verbose_name='是否删除')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '账户',
            },
        ),
    ]
