# Generated by Django 2.0.3 on 2018-04-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('create_time', models.CharField(max_length=19, verbose_name='发表时间')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('read', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('discuss', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_delet', models.IntegerField(default=0, verbose_name='是否已删除')),
                ('author', models.ForeignKey(on_delete=True, to='user_.User', verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '文章详情',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20, unique=True, verbose_name='类别')),
                ('is_delet', models.IntegerField(default=0, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name_plural': '文章类别',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('create_time', models.CharField(max_length=19, verbose_name='评论时间')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('is_delet', models.IntegerField(default=0, verbose_name='是否已删除')),
                ('article', models.ForeignKey(on_delete=True, to='article.Article', verbose_name='文章id')),
                ('user', models.ForeignKey(on_delete=True, to='user_.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '文章评论',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20, unique=True, verbose_name='文章标签')),
                ('is_delet', models.IntegerField(default=0, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name_plural': '文章标签',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=True, to='article.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(on_delete=True, to='article.Tag', verbose_name='标签'),
        ),
    ]
