# Generated by Django 2.0.3 on 2018-05-13 02:32

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(limit_choices_to=models.Q(is_delet=0), on_delete=True, to='user_.User', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(limit_choices_to=models.Q(is_delet=0), on_delete=True, to='article.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(limit_choices_to=models.Q(is_delet=0), on_delete=True, to='article.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='article',
            field=models.ForeignKey(limit_choices_to={'is_delet': 0}, on_delete=True, to='article.Article', verbose_name='文章id'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_delet': 0}, on_delete=True, to='user_.User', verbose_name='用户id'),
        ),
    ]
