# Generated by Django 2.0.3 on 2018-05-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='文件名')),
                ('path', models.CharField(max_length=200, verbose_name='文件所在路径')),
                ('content_type', models.CharField(max_length=50, verbose_name='文件content-type')),
                ('upload_time', models.CharField(max_length=19, verbose_name='上传时间')),
                ('download', models.IntegerField(verbose_name='下载次数')),
                ('is_delet', models.IntegerField(default=0, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name_plural': '文件表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='类型名')),
                ('filetype', models.CharField(max_length=20, unique=True, verbose_name='文件类型')),
                ('is_delet', models.IntegerField(default=0, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name_plural': '文件类别',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.ForeignKey(limit_choices_to={'is_delet': 0}, on_delete=True, to='file.FileType', verbose_name='文件类型'),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_delet': 0}, on_delete=False, to='user_.User', verbose_name='上传人id'),
        ),
    ]
