"""
Django settings for vshare project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9o)ha#2xr5m3c7bve6o3%#6wo5-t_8rw@ka#5w6bg&fq#2zmy^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_',
    'article',
    'mainpage',
    'aboutsite',
    'file',
    'archive',
    # 'haystack',          # 搜索引擎容器
    'DjangoUeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 注册自己的中间件
    'user_.login_check_middleware.LoginCheck',

]

ROOT_URLCONF = 'vshare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 置顶公告上下文
                'aboutsite.topnotice_processor.top_notice',
                # 已登录用户上下文
                'mainpage.logined_user_processor.has_user',
                # 归档信息上下文
                'archive.archive_processor.archive_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'vshare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
# 静态文件
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

TEMPLATE_DIRS = (os.path.join(BASE_DIR,  'templates'),)
# session设置
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # 关闭浏览器，则COOKIE失效

# -----------------需要验证中间件的路由-------------------
LOGIN_AUTH_LIST = [
    '/user_/usercenter',                         # 进入个人主页
    '/file/filecenter',                          # 进入文件中心
    '/file/upload',                              # 上传文件
    '/file/download',                            # 下载文件
    '/article/discuss/',                         # 对别人的文章进行评论
    '/user_/write_article',                      # 自己发表文章
    '/user_/msgboard',                           # 留言给别人
    '/user_/cpwd',                               # 修改密码
    '/user_/cpwdsafe',                           # 修改密保问题
    '/user_/del_art',                            # 删除文章
]

# --------------自定义用户限定相关配置--------------

BASE_FILE_DIR = os.path.join(BASE_DIR, 'files') # 文件存储目录
MAX_USER_SIZE = 99                              # 会员最大数
SIGNAL_MAX_SIZE = 20*(2**20)                    # 单个文件最大20M
VIP_SIGNAL_MAX_SIZE = 5*20*(2**20)              # 特殊用户单个文件大小
ALL_MAX_SIZE = 500*(2**20)    # 500M            # 用户文件仓库容量
VIP_ALL_MAX_SIZE = 20*(2**30) # VIP  20G        # 特殊用户仓库容量
VIP_USER_LIST = ['lujianxin',] #开个小灶         # 特殊用户列表
UP_FILE_CHUNK_SIZE = 5*(2**10)                  # 上传文件分片大小
DOWN_FILE_CHUNK_SIZE = 5*(2**10)                # 下载文件分片大小
FILE_NAME_MAX_SIZE = 100                        # 文件名长度限制
LOGO_FILE_NAME = 'vshare资源.txt'                # 下载时本站logo

#------------------------------------------------
#  编辑器设置
UEDITOR_SETTINGS={
                "images_upload":{
                    "allow_type":"jpg,png,jpeg,bmp",    #定义允许的上传的图片类型
                    "max_size":"2222kb"        #定义允许上传的图片大小，0代表不限制
                },

            }

